Перестарался немного, не заметил сразу доп.инфу в задании
htmlacademy-php/985491-yeticave-12 pull request #10
Opened 2020-07-25 20:04 UTC by Mikhail1000

Перестарался немного, не заметил сразу доп.инфу в задании.
Кривовато как то реализовал, не стал причесывать так как во многих решениях не уверен, что так надо было. Поправлю по замечаниям и уже красиво оформлю.

2020-07-27 14:37 UTC, nkolosov requested changes

2020-07-27 14:37 UTC, nkolosov commented on lot.php
> +require('config.php');
Стоит везде использовать конструкции `include_once` / `require_once` вместо `include`/`require` чтобы избежать возможного дублирования загрузки кода

2020-07-27 14:37 UTC, nkolosov commented on lot.php
> +/*function get_dt_range_back(string $date_create): array {
Код в комментариях не нужно добавлять в репозиторий, нужно удалить

2020-07-27 14:37 UTC, nkolosov commented on lot.php
> +  $id = $_GET['id'];
Здесь стоит привести переменную к типу `int`

2020-07-27 14:37 UTC, nkolosov commented on lot.php
> +  exit("Ошибка подключения: 404 Not found");
Слова "Ошибка подключения" тут не совсем корректны, "Задание с ID N не найдено"более корректно

2020-07-27 14:37 UTC, nkolosov commented on templates/content_lot.php
> +            <img src="../<?=$open_lot['url_image'] ?>" width="730" height="548" alt="Сноуборд">
Ссылка на картинку не должна задаваться относительным путём, должен быть URL на основе корня сайта

2020-07-27 14:37 UTC, nkolosov commented on templates/main.php
> +                    <h3 class="lot__title"><a class="text-link" href="/lot.php<?='?id=' . $product['id'] ?>"><?=htmlspecialchars($product['name']) ?></a></h3>
Лучше вынести константную строку из PHP-кода, чтобы получилось что-то вроде `lot.php?id=<?= $id ?>`

2020-07-27 14:37 UTC, nkolosov commented on lot.php
> +$connect = mysqli_connect("localhost", "mysql", "mysql", "yeticave");
Подключение к БД стоит вынести в `config.php` или в отдельный файл, чтобы не дублировать эту логику на всех страницах заново

2020-07-28 11:50 UTC, nkolosov requested changes

2020-07-28 11:50 UTC, nkolosov commented on lot.php
> +  settype($id, 'integer');
Не надо использовать `settype`, лучше `$id = (int) $_GET['id'];`

2020-07-28 11:50 UTC, nkolosov commented on lot.php
> +if ($open_lot==NULL) {
Всегда необходимо использовать строгое сравнение, `===` вместо `==`

2020-07-28 13:38 UTC, Mikhail1000 commented on lot.php
> +  settype($id, 'integer');
А они равнозначны? Без разницы по  результату? Просто короче запись и все?

2020-07-28 15:14 UTC, merged