Проблема
htmlacademy-php/985491-yeticave-12 pull request #11
Opened 2020-08-01 08:13 UTC by Mikhail1000

2020-08-03 04:33 UTC, nkolosov requested changes

2020-08-03 04:33 UTC, nkolosov commented on add.php
> +$added_lot['date_create'] = date('Y-m-d H:i:s', $timestamp = strtotime("now"));
Для текущей даты вторым параметром не надо ничего передавать, кроме того - здесь вернется результат присваивания, а не значение функции.
Если уж так, то правильно `date('Y-m-d H:i:s', strtotime('now'))`, но лучше оставить просто `date('Y-m-d H:i:s')`

2020-08-03 04:33 UTC, nkolosov commented on add.php
> +  " . $lot_rate . "', '" . $added_lot['lot-date'] . "', '" . $added_lot['lot-step'] . "', '" . $added_lot['author'] . "',
Из-за того, что после `'` есть перенос строки - получается значение-строка, а не число `' 123'` вместо `'123'`

2020-08-03 04:33 UTC, nkolosov commented on add.php
> +  " . $lot_rate . "', '" . $added_lot['lot-date'] . "', '" . $added_lot['lot-step'] . "', '" . $added_lot['author'] . "',
Здесь будет проще с форматированием, если использовать prepared statements или `sprintf` хотя бы

2020-08-06 17:25 UTC, Mikhail1000 commented on add.php
> +  " . $lot_rate . "', '" . $added_lot['lot-date'] . "', '" . $added_lot['lot-step'] . "', '" . $added_lot['author'] . "',
Я там в строках 97-103 пробовал подготовленные выражения, тоже сохранение не проходило, попробую sprintf.

2020-10-08 14:51 UTC, nkolosov requested changes

2020-10-08 14:51 UTC, nkolosov commented on add.php
> +function proverkaFormataDati($data){
Функции не должны именоваться транслитом, используем только английский язык и английские слова.
Тоже самое касается переменных.

Кроме того, у всех функций должен указываться тип для аргументов и тип возвращаемого значения

2020-10-08 14:51 UTC, nkolosov commented on add.php
> +  if ($_POST['lot-rate'] <= 0) {$errors_validate['lot-rate'] = 'Начальная цена должна быть больше нуля';}
Валидацию лучше всего сделать по тому же принципу, что описан в учебнике https://up.htmlacademy.ru/php/12/book/6.5

2020-10-08 14:51 UTC, nkolosov commented on add.php
> +    if (!($type_file == 'image/jpeg' || $type_file == 'image/png')) { $errors_validate['file_img_lot_mime'] = 'Допустимы только файлы изображений типов jpeg и png';  }
Не хватает переносов строк, код должен быть отформатирован.

Кроме того, везде используем строгое сравнение (`===` вместо `==`)

2020-10-08 14:51 UTC, nkolosov commented on templates/content_add_lot.php
> +          <span class="form__error">Введите наименование лота</span>
Здесь нужно выводить саму ошибку в случае её наличия. Аналогично в других полях

2020-10-09 17:21 UTC, Mikhail1000 commented on add.php
> +  if ($_POST['lot-rate'] <= 0) {$errors_validate['lot-rate'] = 'Начальная цена должна быть больше нуля';}
Я так понимаю это относится к порядку действий

2020-10-10 09:33 UTC, Mikhail1000 commented on templates/content_add_lot.php
> +          <span class="form__error">Введите наименование лота</span>
Слегка отредактировал текст, хотя фраза "Введите наименование лота" и подобные вроде тоже указывают на ошибку.

2020-10-11 15:22 UTC, nkolosov requested changes

2020-10-11 15:22 UTC, nkolosov commented on add.php
> +  if ( preg_match($pattern, $date, $razdeli) ) :
Можно сделать проще, используя функцию `date_create_from_format`, не надо пока использовать регулярные выражения.

https://www.php.net/manual/ru/function.date-create-from-format.php

Ну и проблема с наименованием, переменная `razdeli` транслитом

2020-10-11 15:22 UTC, nkolosov commented on add.php
> +/*function validate_form_add_lot (array $required_fields): void {
Закомментированный код надо удалять

2020-10-11 15:22 UTC, nkolosov commented on add.php
> +$sql_read_id_category = "SELECT id FROM categories WHERE name ='" . $_POST['category'] ."'";
Потенциальная SQL-иньекция.
Я могу вместо `category` передать специальносформированную строку и получить доступ к базе данных

2020-10-11 15:22 UTC, nkolosov commented on add.php
> +if (isset($_POST['lot-name'])) {  //Если есть такое поле в POST, значит форма отправлена
Опять же, не верно, я могу передать все поля кроме этого

2020-10-11 15:22 UTC, nkolosov commented on add.php
> +  foreach ($required_fields as $field) {
Здесь написано внтури тоже самое, что и в функции `getPostVal`, которая объявлена выше

2020-10-11 15:22 UTC, nkolosov commented on add.php
> +    move_uploaded_file($_FILES['file_img_lot']['tmp_name'], $file_path . $file_name);
Здесь стоит проверить, что результат выполнения этой функции - успешен. По каким-то причинам файл может не загрузиться (например, может не существовать директория `uploads` или нет прав на запись (как это у меня произошло сразу после загрузки работы на проверку)

Кроме того, другой пользователь может загрузить файл и с таким же названиям и он перетрёт данные кого-то другого.
Имя файла в директории должно быть уникальным.

2020-10-11 15:22 UTC, nkolosov commented on add.php
> +  if (!($type_file === 'image/jpeg' || $type_file === 'image/png')) {
Тут получается, что файл `.jpeg` загружается, а вот `jpg` - нет, это тоже не очень хорошо

2020-10-11 15:22 UTC, nkolosov commented on add.php
> +    $sql_insert_lot = "INSERT INTO lots (date_create, name, description, url_image, start_price, date_end, step_price, author, category) VALUES ('" . $added_lot['date_create'] . "', '" . $added_lot['
И здесь тоже SQL-иньекция, стоит использовать prepared statements

2020-10-11 15:22 UTC, nkolosov commented on add.php
> +    //Получаем из БД данные по только что добавленному лоту
В случае успеха, нужно не отобразить страницу нового лота, а именно - переадресовать (на адрес `lot.php?id=ID`) при помощи функции`header`

2020-10-11 15:22 UTC, nkolosov commented on add.php
> +    $errors_validate['category'] = 'Не выбрана категория';
Можно выбрать несуществующую категорию

2020-10-11 15:22 UTC, nkolosov commented on templates/content_add_lot.php
> +          <span class="form__error">Не введено наименование лота</span>
Здесь должны выводиться ошибки из `$errors_validate` (и в других полях - аналогично)

2020-10-11 15:23 UTC, nkolosov commented on add.php
> +  if ($_POST['lot-rate'] <= 0) {$errors_validate['lot-rate'] = 'Начальная цена должна быть больше нуля';}
Ну, да, но там фактически поэтапно реализуется проверка формы, и итоговый код подходит для любой формы и выглядит гораздо лучше

2020-10-14 16:19 UTC, Mikhail1000 commented on add.php
> +    $errors_validate['category'] = 'Не выбрана категория';
Организовал проверку что категория существует.

2020-10-17 07:31 UTC, nkolosov requested changes

2020-10-17 07:31 UTC, nkolosov commented on add.php
> +  $format_date = date_create_from_format('Y-m-j', $date);
Формат неверный

2020-10-17 07:31 UTC, nkolosov commented on add.php
> +  $added_lot['category'] = $id_select_category['id'];
Код стоит разделить на смысловые блоки, сейчас его очень сложно воспринимать.

То есть сначала делаем всю валидацию, а затем - запись данных в БД (если валидация успешна)

При этом надо выделить в отдельные функции валидацию каждого из полей. 

В учебнике есть очень удобный код для всего этого, фактически надо просто взять код из учебника и немного адаптировать его под свои нужды, а не изобретать велосипед

2020-10-17 07:31 UTC, nkolosov commented on add.php
> +    if (file_exists($file_path . $file_name)) {
Можно сделать сильно проще, просто использовать вместо имени файла его `id` из БД, например

2020-10-19 11:19 UTC, nkolosov requested changes

2020-10-19 11:19 UTC, nkolosov commented on add.php
> +   if ($format_date === false){
Можно проосто написать `return $format_date !== false;`

2020-10-19 11:19 UTC, nkolosov commented on add.php
> +function getPostVal(string $name): string {
Функция нигде не используется

2020-10-19 11:19 UTC, nkolosov commented on add.php
> +//здесь не указан тип возвращаемого значения т.к. при указании string выдает ошибку, я так понимаю что когда ошибки нет он возвращает NULL
Правильнее делать так, чтобы функции, которые занимаются одним и тем же (напимер, валидацией), работали в целом по одному принципу.

То есть всегда возвращали `true`/`false` или всегда - текст ошибки. А сейчас они все работают по разному (и именуются в разном стиле, где-то `camelCase`, где-то `under_score`.

Для восприятия кода очень важно единообразие.

А что касается именно указания типа `string` и отсутствия значения - с PHP 7.1 есть возможность указывать nullable-типы.
Например `function foo(): ?string` может вернуть `string` или `null`

2020-10-19 11:19 UTC, nkolosov commented on add.php
> +//здесь не указан тип возвращаемого значения т.к. при указании string выдает ошибку, я так понимаю что когда ошибки нет он возвращает NULL
И опять же, помимо указания типа возвращаемого значения, надо обязательно указывать и тип для аргументов функции

2020-10-19 11:19 UTC, nkolosov commented on add.php
> +    global $errors_validate;
В коде не должно быть глобальных переменных
```
Б11. Нет глобальных переменных.
Использование глобальных переменных не допускается. Этот запрет не относится к константам.

Глобальными переменными считаются переменные, определенные с ключевым словом global.
```

2020-10-19 11:19 UTC, nkolosov commented on add.php
> +      exit("Страница с id =" . $id . " не найдена.");
Кажется, что в случае ошибки будет ещё одна ошибка, т..к переменная `$id` не существует

2020-10-19 11:19 UTC, nkolosov commented on templates/content_add_lot.php
> +      <div class="form__item form__item--file <?php if($errors_validate['file_img_lot'] || $errors_validate['file_img_lot_mime'] || $errors_validate['file_img_lot_error_move']): ?> form__item--invali
Чтобы было проще отображатть ошибки, в массиве `$errors` нужно иметь только один ключ на одно поле, чтобы получилось что-то такое после валидации
```
$errors = [
'file' => ['ошибка 1', 'ошибка 2'],
'title' => ['ошибка 1'],
];
```
Тогда и проверить наличие ошибки можно без дополнительных условий через `||` и вывести в одну строку все ошибки `echo implode('<br />', $errors['field'])`

2020-10-19 16:26 UTC, Mikhail1000 commented on add.php
> +function getPostVal(string $name): string {
Она используется в content_add_lot, в шаблоне.

2020-10-19 16:44 UTC, Mikhail1000 commented on add.php
> +      exit("Страница с id =" . $id . " не найдена.");
Подставил существующую

2020-10-19 16:45 UTC, Mikhail1000 commented on add.php
> +      exit("Страница с id =" . $id . " не найдена.");
$id_last_insert_lot

2020-10-19 20:17 UTC, Mikhail1000 commented on add.php
> +//здесь не указан тип возвращаемого значения т.к. при указании string выдает ошибку, я так понимаю что когда ошибки нет он возвращает NULL
Пришлось в явном виде NULL выдавать, иначе ошибку выдавал

2020-10-20 13:12 UTC, nkolosov requested changes

2020-10-20 13:12 UTC, nkolosov commented on user_function.php
> +$rules = [
А вот это уже скорее должно остаться в файле `add.php`

2020-10-20 13:12 UTC, nkolosov commented on user_function.php
> +function validate_filled(string $name): ?string {
Я уже говорил про единообразие, почему `validation_format_date` возвращает `true`/`false`, а `validate_filled` `string`/`null` ?

2020-10-20 13:12 UTC, nkolosov commented on user_function.php
> +      $category_exists = 0;
Если переменная имеет значения `0`/`1`, то скорее всего надо, чтобы значениями были `true`/`false`

2020-10-20 13:12 UTC, nkolosov commented on user_function.php
> +      return NULL;
Не хватает проверки, что это вообще число, а не строка, например.

2020-10-20 13:12 UTC, nkolosov commented on user_function.php
> +      $hours_and_minuts_2 = get_dt_range($_POST['lot-date']); //получение массива с часами и минутами разницы времени между введенной датой окончания торгов и текущей датой
`get_dt_range` нужно именно для форматирования даты в часы и минуты, для валидации лучше использовать сравнение `strtotime` и `time`

2020-10-20 13:12 UTC, nkolosov commented on templates/content_add_lot.php
> +            <option>Выберите категорию</option>
Это не должно быть отдельным вариантом выбора. У `select` есть полезный атрибут `prompt` для этого

2020-10-20 13:12 UTC, nkolosov commented on templates/content_add_lot.php
> +              <option <?php if($category['name'] === get_post_val('category')): ?> selected <?php endif; ?> ><?=htmlspecialchars($category['name']) ?></option>
По правильному, надо передавать `value` в теге `option` (и обычно в качестве `value` используется `id`, например)

2020-10-20 13:12 UTC, nkolosov commented on templates/content_add_lot.php
> +    <form class="form form--add-lot container <?php if($errors_validate): ?> form--invalid <?php endif; ?> " action="add.php" method="post" enctype="multipart/form-data"> <!-- form--invalid -->
`$errors_validate` является массивом, а в условии `if` должно быть булевое выражение. 
Здесь скорее надо проверять, что массив не пустой, например.

2020-10-20 13:12 UTC, nkolosov commented on templates/content_add_lot.php
> +        <div class="form__item <?php if($errors_validate['lot-name']): ?> form__item--invalid <?php endif; ?> "> <!-- form__item--invalid -->
Если включить вывод ошибок и предупреждений интерпретатора PHP, то при загрузке страницы можно увидеть кучу подобных сообщений из-за того, что в условии обращение к элекменту массива
```
PHP message: PHP Notice:  Undefined index: lot-name in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 14
PHP message: PHP Notice:  Undefined index: lot-name in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 17
PHP message: PHP Notice:  Undefined index: category in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 19
PHP message: PHP Notice:  Undefined index: category in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 27
PHP message: PHP Notice:  Undefined index: message in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 30
PHP message: PHP Notice:  Undefined index: message in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 33
PHP message: PHP Notice:  Undefined index: lot-rate in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 46
PHP message: PHP Notice:  Undefined index: lot-rate in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 49
PHP message: PHP Notice:  Undefined index: lot-step in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 51
PHP message: PHP Notice:  Undefined index: lot-step in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 54
PHP message: PHP Notice:  Undefined index: lot-date in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 56
PHP message: PHP Notice:  Undefined index: lot-date in /home/nkolosov/Projects/htmlacademy/mten-yeticave/templates/content_add_lot.php on line 59
```

```
С самым строгим уровнем репортинга ошибок (error_reporting = E_ALL) код личного проекта не должен вызывать никаких ошибок и предупреждений.

Исключением являются ошибки типа «Warning», возникающие при использовании функций mysqli_.
```

```
При работе с массивами или объектами обязательно проверять на существование ключа массива/свойства объекта перед обращением к нему.

Следует использовать функции isset или empty, для объектов — isset или property_exists.
```

2020-10-20 13:12 UTC, nkolosov commented on templates/content_add_lot.php
> +        <textarea id="message" name="message" placeholder="Напишите описание лота"><?=get_post_val('message'); ?></textarea>
Если использовать `get_post_val` для вывода данных, то получится ошибка, так как это - пользовательские данные и вывод не фильтруется
```
Б16. Пользовательские данные фильтруются при выводе.
Нефильтрованный вывод информации, полученной от пользователя, опасен, т.к. возможна XSS атака. Необходимо всегда проводить очистку пользовательских данных перед их выводом функциями strip_tags (если теги не нужны) или htmlspecialchars (если теги должны быть заменены на HTML-сущности).
```

2020-10-20 13:12 UTC, nkolosov commented on add.php
> +    mysqli_stmt_execute($stmt);
Здесь не хватает проверки, что данные успешно записаны в БД

2020-10-20 13:12 UTC, nkolosov commented on add.php
> +  if(strpos($result_validate_file, 'uploads') !== false) {
Что это за проверка?

2020-10-20 13:12 UTC, nkolosov commented on add.php
> +        if ($key == 'category') {
Так, конечно, можно, но лучше так не делать.
Правильнее будет передать категории в функцию при её объявлении при помощи замыкания. Выглядит это примерно так
```
$categories = ....;
...
'category' => function () use ($categories) {
...
}
```

2020-10-20 13:12 UTC, nkolosov commented on add.php
> +    $content_page = include_template('content_add_lot.php', $data = ['categories' => $categories, 'errors_validate' => $errors_validate]);
А что за присваивание `$data = []` в качестве аргумента функции?

2020-10-20 16:16 UTC, Mikhail1000 commented on add.php
> +    $content_page = include_template('content_add_lot.php', $data = ['categories' => $categories, 'errors_validate' => $errors_validate]);
Полез вспоминать, нашел

function include_template($name, array $data = []) {
    $name = 'templates/' . $name;
    $result = '';

    if (!is_readable($name)) {
        return $result;
    }

    ob_start();
    extract($data);
    require $name;

    $result = ob_get_clean();

    return $result;
}

2020-10-20 16:16 UTC, Mikhail1000 commented on add.php
> +    $content_page = include_template('content_add_lot.php', $data = ['categories' => $categories, 'errors_validate' => $errors_validate]);
Это в свое время из файла helpers скопировал, а там это было, так и пошло. Уберу сейчас.

2020-10-22 19:28 UTC, nkolosov requested changes

2020-10-22 19:28 UTC, nkolosov commented on config.php
> +$name_folder_uploads_file = '/uploads/';  // Папка с загруженными файлами
Кажется, что стоит сделать это константой, а не переменной

2020-10-22 19:28 UTC, nkolosov commented on user_function.php
> +    return htmlspecialchars($_POST[$name]) ?? "";
Проще написать `return htmlspecialchars(get_post_val($name))`

2020-10-22 19:28 UTC, nkolosov commented on add.php
> +      $time_before_end_lot = floor($time_before_end_lot/3600);  // Переводим в часы
Можно не делать лишней операции и сравнить `strtotime($_POST['lot-date']) < time() + 86400`

2020-10-22 19:28 UTC, nkolosov commented on add.php
> +      if ($_POST['category'] === 'Выберите категорию') {
Но ведь в такой ситуации в любом случае `$category_exists === false` ?

2020-10-28 09:54 UTC, merged