Аутентификация
htmlacademy-php/985491-yeticave-12 pull request #13
Opened 2020-11-11 14:07 UTC by Mikhail1000

2020-11-13 12:09 UTC, nkolosov requested changes

2020-11-13 12:09 UTC, nkolosov commented on logout.php
> +unset($_SESSION['user_id']);
Лучше сделать `$_SESSION = []`, чтобы при добавлении каких-то ключей не пришлось менять код

2020-11-13 12:09 UTC, nkolosov commented on sign_in.php
> +];
Хорошей практикой является  не делить ошибки на ошибки логина и пароля, а писать "Неверный e-mail или пароль", это не позволяет злоумышленнику найти "какие логины существуют"

2020-11-13 12:09 UTC, nkolosov commented on sign_in.php
> +    session_start();
Лучше делать `session_start` в начале каждого файла (например, там же, где создается коннект к БД и потом подключается ко всем остальным)

2020-11-13 12:09 UTC, nkolosov commented on templates/content_lot.php
> +              <?php foreach ($bet_open_lot as $bet): ?>
Если ставок не будет, в логах будет PHP warning (итерирование по пустому массиву)

2020-11-14 09:32 UTC, Mikhail1000 commented on sign_in.php
> +    session_start();
Вынес в config.php

2020-11-16 13:31 UTC, merged