Создание БД
htmlacademy-php/985491-yeticave-12 pull request #7
Opened 2020-07-13 17:49 UTC by Mikhail1000

2020-07-14 09:59 UTC, nkolosov requested changes

2020-07-14 09:59 UTC, nkolosov commented on schema.sql
> +  name CHAR(64),
Не хватает `NOT NULL` для полей

2020-07-14 09:59 UTC, nkolosov commented on schema.sql
> +  author INT,
Для полей, которые содержат `id` из других таблиц нужно указывать внешние ключи

2020-07-14 09:59 UTC, nkolosov commented on schema.sql
> +  price DECIMAL NOT NULL,
Для цены лучше использовать `INT` (и сохранять там число в копейках/центах и т.п.), а при отображении уже делить на 100)

2020-07-14 09:59 UTC, nkolosov commented on schema.sql
> +  created_lot INT,
Что здесь будет храниться? Если количество созданных лотов, то это избыточно

2020-07-14 09:59 UTC, nkolosov commented on schema.sql
> +  email VARCHAR(128) NOT NULL UNIQUE,
Некорректное ограничение, по спецификации email может быть длиннее 128 символов

2020-07-14 09:59 UTC, nkolosov commented on schema.sql
> +  password CHAR(64),
Пароль в открытом виде не будет хранится, а в хеши бывают и длиннее 64 символов

2020-07-14 09:59 UTC, nkolosov commented on schema.sql
> +  name CHAR(64) NOT NULL UNIQUE,
Имя - не уникальное свойство

2020-07-14 14:16 UTC, Mikhail1000 commented on schema.sql
> +  password CHAR(64),
Скольки символов тогда достаточно? Я из примера academy взял.

2020-07-19 10:21 UTC, nkolosov requested changes

2020-07-19 10:21 UTC, nkolosov commented on schema.sql
> +  FOREIGN KEY (author)  REFERENCES users (id),
А зачем ключи и индексы закомментированны?

2020-07-19 10:21 UTC, nkolosov commented on schema.sql
> +  description TEXT,
Согласно ТЗ, описание - обязательное поле

2020-07-19 10:21 UTC, nkolosov commented on schema.sql
> +  author INT,
Автор, категория и т.п. - обязательные поля

2020-07-19 10:21 UTC, nkolosov commented on schema.sql
> +);
Список категорий известен заранее, можно добавить после создания таблицы соответствующие INSERT'ы в БД

2020-07-19 10:21 UTC, nkolosov commented on schema.sql
> +  bet INT/*,
А что хранится в этом поле, зачем оно нужно?

2020-07-19 10:21 UTC, nkolosov commented on schema.sql
> +  email VARCHAR(254) NOT NULL UNIQUE,
E-mail может быть длинее 254 символов, как и имя - длиннее 64, лучше тут использовать тоже тип TEXT.
А на поле email не хватает индекса

2020-07-19 13:09 UTC, Mikhail1000 commented on schema.sql
> +  bet INT/*,
created lot - внешний ключ на id созданных данным пользователем лотов, bet - то же, но на созданные данным пользователем ставки.

2020-07-19 13:09 UTC, Mikhail1000 commented on schema.sql
> +  bet INT/*,
В ТЗ они стоят и именно так описаны.

2020-07-19 13:15 UTC, Mikhail1000 commented on schema.sql
> +  email VARCHAR(254) NOT NULL UNIQUE,
https://qna.habr.com/q/299136
https://codengineering.ru/q/what-is-the-maximum-length-of-a-valid-email-address-26769/
Я просто погуглил писали про 254 символа, я сейчас исправлю на 320. Или это неверная информация?

2020-07-19 13:16 UTC, Mikhail1000 commented on schema.sql
> +  email VARCHAR(254) NOT NULL UNIQUE,
А для чего позволять делать настолько длинные имена? Их же и отображать потом неудобно.

2020-07-19 13:33 UTC, Mikhail1000 commented on schema.sql
> +  email VARCHAR(254) NOT NULL UNIQUE,
Нет, пока вернул на 254, по email, иначе не удается индекс потом сделать, когда ставишь тип TEXT, и делаешь на это поле индекс, выдает ошибку, в HeidiSQL.

2020-07-19 13:46 UTC, nkolosov requested changes

2020-07-19 13:46 UTC, nkolosov commented on schema.sql
> +  email VARCHAR(254) NOT NULL UNIQUE,
Ну, на самом делее ок, пусть останется 254.
Действительно, сделать индекс на TEXT не получится

2020-07-19 13:46 UTC, nkolosov commented on schema.sql
> +  bet INT/*,
Один пользователь может сделать несколько лотов и ставок, так что сохранить их в одно поле у пользователя непосредственно - не выйдет.

Поэтому внешним ключом будет являться поле юзер для лотов и ставок, которое будет ссылаться на эту таблицу

2020-07-20 14:56 UTC, merged